# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_TestWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestWindow(object):
    def setupUi(self, TestWindow):
        TestWindow.setObjectName("TestWindow")
        TestWindow.resize(640, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(TestWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(TestWindow)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.param_to_load = QtWidgets.QPushButton(self.widget)
        self.param_to_load.setObjectName("param_to_load")
        self.gridLayout_4.addWidget(self.param_to_load, 3, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 1, 1, 1)
        self.model_to_load = QtWidgets.QComboBox(self.widget)
        self.model_to_load.setObjectName("model_to_load")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.gridLayout_4.addWidget(self.model_to_load, 2, 2, 1, 1)
        self.acc_to_load = QtWidgets.QComboBox(self.widget)
        self.acc_to_load.setObjectName("acc_to_load")
        self.acc_to_load.addItem("")
        self.acc_to_load.addItem("")
        self.gridLayout_4.addWidget(self.acc_to_load, 4, 2, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setObjectName("start_button")
        self.gridLayout_4.addWidget(self.start_button, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 1, 1, 1)
        self.use_GPU = QtWidgets.QCheckBox(self.widget)
        self.use_GPU.setObjectName("use_GPU")
        self.gridLayout_4.addWidget(self.use_GPU, 5, 1, 1, 1)
        self.dataset_to_load = QtWidgets.QComboBox(self.widget)
        self.dataset_to_load.setObjectName("dataset_to_load")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.gridLayout_4.addWidget(self.dataset_to_load, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.dataset_layout = QtWidgets.QGridLayout()
        self.dataset_layout.setObjectName("dataset_layout")
        self.gridLayout_6.addLayout(self.dataset_layout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(TestWindow)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(TestWindow)
        self.model_to_load.currentIndexChanged['int'].connect(TestWindow.load_model)
        self.param_to_load.clicked.connect(TestWindow.load_param)
        self.acc_to_load.currentIndexChanged['int'].connect(TestWindow.load_acc)
        self.start_button.clicked.connect(TestWindow.start)
        self.dataset_to_load.currentIndexChanged['int'].connect(TestWindow.load_dataset)
        QtCore.QMetaObject.connectSlotsByName(TestWindow)

    def retranslateUi(self, TestWindow):
        _translate = QtCore.QCoreApplication.translate
        TestWindow.setWindowTitle(_translate("TestWindow", "测试"))
        self.param_to_load.setText(_translate("TestWindow", "选择"))
        self.label_2.setText(_translate("TestWindow", "选择模型参数"))
        self.label.setText(_translate("TestWindow", "选择要加载的模型"))
        self.model_to_load.setItemText(0, _translate("TestWindow", "<None>"))
        self.model_to_load.setItemText(1, _translate("TestWindow", "从文件加载"))
        self.model_to_load.setItemText(2, _translate("TestWindow", "resnet18"))
        self.model_to_load.setItemText(3, _translate("TestWindow", "resnet50_32x4d"))
        self.model_to_load.setItemText(4, _translate("TestWindow", "wide_resnet50_2"))
        self.model_to_load.setItemText(5, _translate("TestWindow", "alexnet"))
        self.model_to_load.setItemText(6, _translate("TestWindow", "vgg16"))
        self.model_to_load.setItemText(7, _translate("TestWindow", "squeezenet1_0"))
        self.model_to_load.setItemText(8, _translate("TestWindow", "densenet161"))
        self.model_to_load.setItemText(9, _translate("TestWindow", "inception_v3"))
        self.model_to_load.setItemText(10, _translate("TestWindow", "goglenet"))
        self.model_to_load.setItemText(11, _translate("TestWindow", "mobilenet_v2"))
        self.acc_to_load.setItemText(0, _translate("TestWindow", "默认"))
        self.acc_to_load.setItemText(1, _translate("TestWindow", "自定义"))
        self.start_button.setText(_translate("TestWindow", "启动"))
        self.label_3.setText(_translate("TestWindow", "选择准确率函数"))
        self.use_GPU.setText(_translate("TestWindow", "使用GPU运行"))
        self.dataset_to_load.setItemText(0, _translate("TestWindow", "<None>"))
        self.dataset_to_load.setItemText(1, _translate("TestWindow", "从文件加载"))
        self.dataset_to_load.setItemText(2, _translate("TestWindow", "MINST"))
        self.dataset_to_load.setItemText(3, _translate("TestWindow", "ImageNet"))
        self.dataset_to_load.setItemText(4, _translate("TestWindow", "CIFAR10"))
        self.label_4.setText(_translate("TestWindow", "选择数据集"))

