# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_TrainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UI_TrainWindow(object):
    def setupUi(self, UI_TrainWindow):
        UI_TrainWindow.setObjectName("UI_TrainWindow")
        UI_TrainWindow.resize(746, 667)
        self.gridLayout_2 = QtWidgets.QGridLayout(UI_TrainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.log = QtWidgets.QTextBrowser(UI_TrainWindow)
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_3 = QtWidgets.QWidget(UI_TrainWindow)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.loss_layout = QtWidgets.QGridLayout()
        self.loss_layout.setObjectName("loss_layout")
        self.gridLayout_6.addLayout(self.loss_layout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 5, 0, 1, 2)
        self.widget = QtWidgets.QWidget(UI_TrainWindow)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pretrained_layout = QtWidgets.QVBoxLayout()
        self.pretrained_layout.setObjectName("pretrained_layout")
        self.verticalLayout_2.addLayout(self.pretrained_layout)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 2)
        self.widget_2 = QtWidgets.QWidget(UI_TrainWindow)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dataset_layout = QtWidgets.QGridLayout()
        self.dataset_layout.setObjectName("dataset_layout")
        self.gridLayout_5.addLayout(self.dataset_layout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 3, 0, 1, 2)
        self.model_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.model_to_load.setObjectName("model_to_load")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.gridLayout_3.addWidget(self.model_to_load, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(UI_TrainWindow)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(UI_TrainWindow)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.loss_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.loss_to_load.setObjectName("loss_to_load")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.gridLayout_3.addWidget(self.loss_to_load, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(UI_TrainWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.optim_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.optim_to_load.setObjectName("optim_to_load")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.gridLayout_3.addWidget(self.optim_to_load, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(UI_TrainWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.dataset_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.dataset_to_load.setObjectName("dataset_to_load")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.gridLayout_3.addWidget(self.dataset_to_load, 2, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(UI_TrainWindow)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.optim_layout = QtWidgets.QGridLayout()
        self.optim_layout.setObjectName("optim_layout")
        self.gridLayout_7.addLayout(self.optim_layout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 7, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.bottom_layout = QtWidgets.QGridLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        self.gridLayout.addLayout(self.bottom_layout, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.halt_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.halt_button.setObjectName("halt_button")
        self.horizontalLayout.addWidget(self.halt_button)
        self.reset_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.show_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.show_button.setObjectName("show_button")
        self.horizontalLayout.addWidget(self.show_button)
        self.load_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout.addWidget(self.load_button)
        self.save_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)

        self.retranslateUi(UI_TrainWindow)
        self.model_to_load.currentIndexChanged['int'].connect(UI_TrainWindow.load_model)
        self.dataset_to_load.currentIndexChanged['int'].connect(UI_TrainWindow.load_dataset)
        self.loss_to_load.currentIndexChanged['int'].connect(UI_TrainWindow.load_loss_function)
        self.optim_to_load.currentIndexChanged['int'].connect(UI_TrainWindow.load_optim)
        self.start_button.clicked.connect(UI_TrainWindow.start)
        self.halt_button.clicked.connect(UI_TrainWindow.stop)
        self.reset_button.clicked.connect(UI_TrainWindow.reset)
        self.show_button.clicked.connect(UI_TrainWindow.show_result)
        self.load_button.clicked.connect(UI_TrainWindow.load_script)
        self.save_button.clicked.connect(UI_TrainWindow.save)
        QtCore.QMetaObject.connectSlotsByName(UI_TrainWindow)

    def retranslateUi(self, UI_TrainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_TrainWindow.setWindowTitle(_translate("UI_TrainWindow", "训练"))
        self.model_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.model_to_load.setItemText(1, _translate("UI_TrainWindow", "从文件中加载"))
        self.model_to_load.setItemText(2, _translate("UI_TrainWindow", "resnet18"))
        self.model_to_load.setItemText(3, _translate("UI_TrainWindow", "resnet50_32x4d"))
        self.model_to_load.setItemText(4, _translate("UI_TrainWindow", "wide_resnet50_2"))
        self.model_to_load.setItemText(5, _translate("UI_TrainWindow", "alexnet"))
        self.model_to_load.setItemText(6, _translate("UI_TrainWindow", "vgg16"))
        self.model_to_load.setItemText(7, _translate("UI_TrainWindow", "squeezenet1_0"))
        self.model_to_load.setItemText(8, _translate("UI_TrainWindow", "densenet161"))
        self.model_to_load.setItemText(9, _translate("UI_TrainWindow", "inception_v3"))
        self.model_to_load.setItemText(10, _translate("UI_TrainWindow", "goglenet"))
        self.model_to_load.setItemText(11, _translate("UI_TrainWindow", "mobilenet_v2"))
        self.label_4.setText(_translate("UI_TrainWindow", "请选择优化器："))
        self.label.setText(_translate("UI_TrainWindow", "请选择要加载的模型："))
        self.loss_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.loss_to_load.setItemText(1, _translate("UI_TrainWindow", "从文件中加载"))
        self.loss_to_load.setItemText(2, _translate("UI_TrainWindow", "自定义"))
        self.loss_to_load.setItemText(3, _translate("UI_TrainWindow", "L1Loss"))
        self.loss_to_load.setItemText(4, _translate("UI_TrainWindow", "MSELoss"))
        self.loss_to_load.setItemText(5, _translate("UI_TrainWindow", "CrossEntropyLoss"))
        self.loss_to_load.setItemText(6, _translate("UI_TrainWindow", "SoftMarginLoss"))
        self.loss_to_load.setItemText(7, _translate("UI_TrainWindow", "TripletLoss"))
        self.label_3.setText(_translate("UI_TrainWindow", "请选择损失函数："))
        self.optim_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.optim_to_load.setItemText(1, _translate("UI_TrainWindow", "SGD"))
        self.optim_to_load.setItemText(2, _translate("UI_TrainWindow", "Adam"))
        self.optim_to_load.setItemText(3, _translate("UI_TrainWindow", "Adadelta"))
        self.optim_to_load.setItemText(4, _translate("UI_TrainWindow", "RMSprop"))
        self.label_2.setText(_translate("UI_TrainWindow", "请选择要加载的数据集："))
        self.dataset_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.dataset_to_load.setItemText(1, _translate("UI_TrainWindow", "从文件中加载"))
        self.dataset_to_load.setItemText(2, _translate("UI_TrainWindow", "自定义"))
        self.dataset_to_load.setItemText(3, _translate("UI_TrainWindow", "MNIST"))
        self.dataset_to_load.setItemText(4, _translate("UI_TrainWindow", "COCO_Caption"))
        self.dataset_to_load.setItemText(5, _translate("UI_TrainWindow", "COCO_Detection"))
        self.dataset_to_load.setItemText(6, _translate("UI_TrainWindow", "ImageNet"))
        self.dataset_to_load.setItemText(7, _translate("UI_TrainWindow", "CIFAR"))
        self.start_button.setText(_translate("UI_TrainWindow", "开始"))
        self.halt_button.setText(_translate("UI_TrainWindow", "停止"))
        self.reset_button.setText(_translate("UI_TrainWindow", "重置"))
        self.show_button.setText(_translate("UI_TrainWindow", "显示"))
        self.load_button.setText(_translate("UI_TrainWindow", "加载"))
        self.save_button.setText(_translate("UI_TrainWindow", "保存"))

