# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_TrainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UI_TrainWindow(object):
    def setupUi(self, UI_TrainWindow):
        UI_TrainWindow.setObjectName("UI_TrainWindow")
        UI_TrainWindow.resize(746, 667)
        self.gridLayout_2 = QtWidgets.QGridLayout(UI_TrainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.loss_detail = QtWidgets.QWidget(UI_TrainWindow)
        self.loss_detail.setObjectName("loss_detail")
        self.gridLayout_3.addWidget(self.loss_detail, 3, 0, 1, 2)
        self.optim_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.optim_to_load.setObjectName("optim_to_load")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.optim_to_load.addItem("")
        self.gridLayout_3.addWidget(self.optim_to_load, 4, 1, 1, 1)
        self.dataset_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.dataset_to_load.setObjectName("dataset_to_load")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.dataset_to_load.addItem("")
        self.gridLayout_3.addWidget(self.dataset_to_load, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(UI_TrainWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(UI_TrainWindow)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(UI_TrainWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.model_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.model_to_load.setObjectName("model_to_load")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.model_to_load.addItem("")
        self.gridLayout_3.addWidget(self.model_to_load, 0, 1, 1, 1)
        self.loss_to_load = QtWidgets.QComboBox(UI_TrainWindow)
        self.loss_to_load.setObjectName("loss_to_load")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.loss_to_load.addItem("")
        self.gridLayout_3.addWidget(self.loss_to_load, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(UI_TrainWindow)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.widget = QtWidgets.QWidget(UI_TrainWindow)
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 5, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.log = QtWidgets.QTextBrowser(UI_TrainWindow)
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.halt_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.halt_button.setObjectName("halt_button")
        self.horizontalLayout_2.addWidget(self.halt_button)
        self.reset_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_2.addWidget(self.reset_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.load_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout_3.addWidget(self.load_button)
        self.save_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.show_button = QtWidgets.QPushButton(UI_TrainWindow)
        self.show_button.setObjectName("show_button")
        self.horizontalLayout_3.addWidget(self.show_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)

        self.retranslateUi(UI_TrainWindow)
        self.model_to_load.currentIndexChanged['int'].connect(UI_TrainWindow.load_model)
        QtCore.QMetaObject.connectSlotsByName(UI_TrainWindow)

    def retranslateUi(self, UI_TrainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_TrainWindow.setWindowTitle(_translate("UI_TrainWindow", "训练"))
        self.optim_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.optim_to_load.setItemText(1, _translate("UI_TrainWindow", "SGD"))
        self.optim_to_load.setItemText(2, _translate("UI_TrainWindow", "Adam"))
        self.optim_to_load.setItemText(3, _translate("UI_TrainWindow", "Adadelta"))
        self.optim_to_load.setItemText(4, _translate("UI_TrainWindow", "RMSprop"))
        self.dataset_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.dataset_to_load.setItemText(1, _translate("UI_TrainWindow", "自定义"))
        self.dataset_to_load.setItemText(2, _translate("UI_TrainWindow", "MNIST"))
        self.dataset_to_load.setItemText(3, _translate("UI_TrainWindow", "COCO_Caption"))
        self.dataset_to_load.setItemText(4, _translate("UI_TrainWindow", "COCO_Detection"))
        self.dataset_to_load.setItemText(5, _translate("UI_TrainWindow", "ImageNet"))
        self.dataset_to_load.setItemText(6, _translate("UI_TrainWindow", "CIFAR"))
        self.label_3.setText(_translate("UI_TrainWindow", "请选择损失函数："))
        self.label.setText(_translate("UI_TrainWindow", "请选择要加载的模型："))
        self.label_2.setText(_translate("UI_TrainWindow", "请选择要加载的数据集："))
        self.model_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.model_to_load.setItemText(1, _translate("UI_TrainWindow", "自定义"))
        self.model_to_load.setItemText(2, _translate("UI_TrainWindow", "resnet18"))
        self.model_to_load.setItemText(3, _translate("UI_TrainWindow", "resnet50_32x4d"))
        self.model_to_load.setItemText(4, _translate("UI_TrainWindow", "wide_resnet50_2"))
        self.model_to_load.setItemText(5, _translate("UI_TrainWindow", "alexnet"))
        self.model_to_load.setItemText(6, _translate("UI_TrainWindow", "vgg16"))
        self.model_to_load.setItemText(7, _translate("UI_TrainWindow", "squeezenet1_0"))
        self.model_to_load.setItemText(8, _translate("UI_TrainWindow", "densenet161"))
        self.model_to_load.setItemText(9, _translate("UI_TrainWindow", "inception_v3"))
        self.model_to_load.setItemText(10, _translate("UI_TrainWindow", "goglenet"))
        self.model_to_load.setItemText(11, _translate("UI_TrainWindow", "mobilenet_v2"))
        self.loss_to_load.setItemText(0, _translate("UI_TrainWindow", "<None>"))
        self.loss_to_load.setItemText(1, _translate("UI_TrainWindow", "自定义"))
        self.loss_to_load.setItemText(2, _translate("UI_TrainWindow", "L1Loss"))
        self.loss_to_load.setItemText(3, _translate("UI_TrainWindow", "MSELoss"))
        self.loss_to_load.setItemText(4, _translate("UI_TrainWindow", "CrossEntropyLoss"))
        self.loss_to_load.setItemText(5, _translate("UI_TrainWindow", "SoftMarginLoss"))
        self.loss_to_load.setItemText(6, _translate("UI_TrainWindow", "TripletLoss"))
        self.label_4.setText(_translate("UI_TrainWindow", "请选择优化器："))
        self.start_button.setText(_translate("UI_TrainWindow", "开始"))
        self.halt_button.setText(_translate("UI_TrainWindow", "停止"))
        self.reset_button.setText(_translate("UI_TrainWindow", "重置"))
        self.load_button.setText(_translate("UI_TrainWindow", "加载"))
        self.save_button.setText(_translate("UI_TrainWindow", "保存"))
        self.show_button.setText(_translate("UI_TrainWindow", "显示"))

